import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.ks.logging.StepExecutionLoggingNeutralizerTest

runWithJUnitRunner(StepExecutionLoggingNeutralizerTest.class)